### ISSUE TITLE
Python 3 support

### ISSUE THREAD

**Issue by weatherfrog** [Insightly/insightly-python#11]
Hi,
It would be great if this library would be Python 3 compatible. Looking at the code, it should not be too hard to make it work with both Pyton 2.7 and Python >3.3. Have you considered doing this?

**Comment by brianinsightly** [comment]
Hi. We'll be sticking with 2.7 for now as it is compatible with the largest number of environments, including Google App Engine. That said, there's nothing stopping users from retooling it for v3.

**Comment by weatherfrog** [comment]
Hi, thanks for the immediate response. Ok, will modify it for Python 3 then...

**Comment by brianinsightly** [comment]
Thanks. Watch this space for news about the version 2.2 API release (coming any day now). We'll be updating the Python library with support for that, so once that's out will be a good time to add v3 support.

**Comment by weatherfrog** [comment]
All right, thanks!

**Comment by weatherfrog** [comment]
I fixed a few things to make the library Python 2.7/3.\* compatible. See
https://github.com/meteotest/insightly-python
I also eliminated tab/space inconsistencies, removed unused imports, corrected a misspelled variable name (sub_type_id => subtype_id) and made the file PEP8 compliant (except for line length).
What do you think? Would you accept a pull request?

PS: The `test()` method produces quite some `FAIL` messages (also your original version):

``` python
i = Insightly(apikey='XXXXXXX')
i.test()
[...]
166 of 207 tests passed
```

Is that how it's "supposed" to be?

**Comment by brianinsightly** [comment]
Ok thanks.

Ill take a look.

Brian

**Comment by weatherfrog** [comment]
Any news on that one?

**Comment by brianinsightly** [comment]
Hi, we released version 2.2 of the API yesterday, and also released a new Python SDK. The new SDK has much more complete test cases (see insightlytest.py). We'll be adding some wrapper functions for the most common tasks (e.g. adding and searching contacts), as well.

**Comment by weatherfrog** [comment]
That's nice, thanks.
But what about Python 3 support? It's really not a huge task to make this module work with both Python 2.7 and >=3.3. Our company has been an Insightly customer for 1 year now. The product itself works well, but this is really annoying. I mean, it's 2015... :-)

**Comment by brianinsightly** [comment]
Hi,

If this can be done in a way that is backward compatible, I'm all for it. I
mainly work in Python 2.7 as I do a lot with Google App Engine, which
doesn't support Python 3 (so I haven't had the need to upgrade yet). If you
can point me toward a good resource on upgrading to Python 3, I'll
definitely be glad to do that.

Thanks,

Brian (brian@insightly.com)

**Comment by weatherfrog** [comment]
Sure, it can be done in a backward compatible way. I loosely follow these guides:
http://python-future.org/compatible_idioms.html
http://lucumr.pocoo.org/2011/1/22/forwards-compatible-python/ (pretty old, but still useful)

I think I did the main work at https://github.com/meteotest/insightly-python/commit/d709d41184ab3735eadc3a0ad3f5eb04ff180b76

**Comment by brianinsightly** [comment]
OK thanks for the info. I'll take a look at this in a week or so (on
vacation next week with no internets or phonez).

Brian

**Comment by jebsky** [comment]
I am a Django dev and Ill say that python3 support would make this library actually useful for me. I would expect anyone writing something from scratch would be using 3 these days. 2 is so old I have never even used it.

**Comment by brianinsightly** [comment]
One of the reasons we use 2.7 is to insure compatibility with google app
engine (which uses 2.7). Making it work with both versions is on my to do
list for november btw.

Brian McConnell

**Comment by brianinsightly** [comment]
Hi,

I updated the Python library to work with version 3.x, it should now work
with version 2.7 or 3.x (the tests all pass for both versions so it looks
good).

Brian

On Tue, Oct 27, 2015 at 12:16 PM, Jeffrey Balinsky <notifications@github.com

**Comment by brianinsightly** [comment]
Remau,

I just updated the Python library to work with version 3.x and 2.7. The
automated tests all pass for both versions so it looks good. Let me know if
you have any questions.

Thanks,

Brian
