### ISSUE TITLE
OPPORTUNITY_VALUE fields not updated but no error returned

### ISSUE THREAD

**Issue by odedbd** [Insightly/insightly-python#30]
I'm using the python SDK to updated some opportunities that were updated by my sales team offline. One of the fields that was updated is the OPPORTUNITY_VALUE field. Most of the fields are updated just fine but the OPPORTUNITY_VALUE field doesn't get updated and does not give out any error. 

I have examined the results of i.read('opportunities',top=10) to see what the value field looks like, and from this and the docs I gather it should be an integer. Everything else seems to be updated just fine.

Any ideas?

I am issuing the following code:

```
print 'prepared record:'
print json.dumps(prepared_opportunity_record,indent=4)
print 'update result:'
print json.dumps(i.update('opportunities',prepared_opportunity_record),indent=4)
```

and am getting the following output (I had to sanitize the data for printing here, so all actual insightly ids were replace with 1234567 or similar and field values replaced with "value", opportunity name changed to "Acme" etc.) :

```
prepared record:
{
    "OPPORTUNITY_VALUE": 27000, 
    "OPPORTUNITY_ID": 1234567, 
    "BID_CURRENCY": "AUD", 
    "ACTUAL_CLOSE_DATE": "2016-02-29 00:00:00", 
    "OPPORTUNITY_STATE": "WON", 
    "CUSTOMFIELDS": [
        {
            "FIELD_VALUE": "value", 
            "CUSTOM_FIELD_ID": "OPPORTUNITY_FIELD_4"
        }, 
        {
            "FIELD_VALUE": "value", 
            "CUSTOM_FIELD_ID": "OPPORTUNITY_FIELD_1"
        }, 
        {
            "FIELD_VALUE": "value", 
            "CUSTOM_FIELD_ID": "OPPORTUNITY_FIELD_2"
        }, 
        {
            "FIELD_VALUE": "value", 
            "CUSTOM_FIELD_ID": "OPPORTUNITY_FIELD_3"
        }
    ], 
    "CATEGORY_ID": 1234567, 
    "OPPORTUNITY_NAME": "Acme"
}
update result:
{
    "BID_TYPE": null, 
    "BID_CURRENCY": "AUD", 
    "VISIBLE_TEAM_ID": null, 
    "BID_DURATION": null, 
    "OPPORTUNITY_VALUE": null, 
    "OPPORTUNITY_STATE_REASON_ID": null, 
    "RESPONSIBLE_USER_ID": null, 
    "PROBABILITY": null, 
    "FORECAST_CLOSE_DATE": null, 
    "ACTUAL_CLOSE_DATE": "2016-02-29 00:00:00", 
    "VISIBLE_TO": "EVERYONE", 
    "PIPELINE_ID": 12345, 
    "IMAGE_URL": null, 
    "VISIBLE_USER_IDS": null, 
    "OPPORTUNITY_ID": 1234567, 
    "STAGE_ID": 160890, 
    "DATE_UPDATED_UTC": "2016-04-07 15:02:51", 
    "TAGS": [], 
    "OPPORTUNITY_DETAILS": null, 
    "OPPORTUNITY_STATE": "WON", 
    "CUSTOMFIELDS": [
        {
            "FIELD_VALUE": "value", 
            "CUSTOM_FIELD_ID": "OPPORTUNITY_FIELD_1"
        }, 
        {
            "FIELD_VALUE": "value", 
            "CUSTOM_FIELD_ID": "OPPORTUNITY_FIELD_2"
        }, 
        {
            "FIELD_VALUE": "value", 
            "CUSTOM_FIELD_ID": "OPPORTUNITY_FIELD_3"
        }, 
        {
            "FIELD_VALUE": "value", 
            "CUSTOM_FIELD_ID": "OPPORTUNITY_FIELD_4"
        }
    ], 
    "OPPORTUNITY_NAME": "Acme", 
    "LINKS": [], 
    "BID_AMOUNT": null, 
    "DATE_CREATED_UTC": "2015-11-22 09:00:38", 
    "OWNER_USER_ID": 123456, 
    "CATEGORY_ID": 1234567
}
```

**Comment by brockbr** [comment]
OPPORTUNITY_VALUE is a calculated value based on BID_AMOUNT, BID_TYPE and BID_DURATION.  

The API doesn't actually support the field at all for an Opportunity
https://api.insight.ly/v2.1/Help/Api/PUT-Opportunities

So I'm not quite sure where that came from.

**Comment by brockbr** [comment]
Repost from Support thread at support.insight.ly:

"Opportunity Value" is a calculated value based on BID_AMOUNT, BID_TYPE and BID_DURATION.

The API doesn't actually support the field OPPORTUNITY_VALUE at all for an Opportunity
https://api.insight.ly/v2.1/Help/Api/PUT-Opportunities

I checked the python code and there's no reference to "OPPORTUNITY_VALUE" there either.  Of course, it could be in something old or outdated that I'm not seeing.

**Comment by odedbd** [comment]
@brockbr - thank you for the detailed explanation, I will try using the BID_AMOUNT instead. It might be worthwhile to add some specific comment about this (or any other computed fields) to the API docs. Something to the effect that "the following fields are computed and thus read only in the API" .

**Comment by odedbd** [comment]
@brockbr - using the BID_AMOUNT worked. Thank you for your help!
