### ISSUE TITLE
No support for accents

### ISSUE THREAD

**Issue by RignonNoel** [Insightly/insightly-python#7]
No support for French accents (àéèêë...)
ODataQuery not manage accents and leaves unchanged

return an : "HTTPError: HTTP Error 400: Bad request"

Can i know what encoding use for your application in waiting?

**Comment by brianinsightly** [comment]
Hello, we will be releasing version 2.2 of the API to public beta early next week (Sept 21st). One of the issues we address in this release is an easier way to filter results (we never liked OData that much). Watch the Q&A forum at support.insight.ly for news about the release. Thanks.

Brian McConnell
