### ISSUE TITLE
Problem getOrganizations by id

### ISSUE THREAD

**Issue by RignonNoel** [Insightly/insightly-python#8]
When i want get an organization by id, the url look like that : 
https://api.insight.ly/v2.1/Contacts&ids=1111111&$top=22222

normally it need look like that :
https://api.insight.ly/v2.1/Contacts?ids=1111111&$top=22222

With a "?" and not a "&"

**Comment by brianinsightly** [comment]
Hello, I just saw this issue in the queue (github did not notify me). We will be releasing a major update to the API and the Python SDK next week. Version 2.2 of the API offers substantial improvements in performance and functionality, while the Python SDK has been greatly simplified (~ 700 lines of code, and no external libraries), so watch the Q&A forum at support.insight.ly for news about this. Thanks!

Brian McConnell
Author, Python SDK
